---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-app-account
  namespace: conjurpoc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-cluster
  namespace: conjurpoc
---
apiVersion: v1
kind: Secret
metadata:
  name: conjur-cluster-secret
  namespace: conjurpoc
  annotations:
    kubernetes.io/service-account.name: conjur-cluster
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conjur-authenticator
  namespace: conjurpoc
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator
  namespace: conjurpoc
subjects:
- kind: ServiceAccount
  name: conjur-cluster
  namespace: conjurpoc
roleRef:
  kind: Role
  name: conjur-authenticator
  apiGroup: rbac.authorization.k8s.io
