apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur-poc-jwt
spec:
  provider:
    conjur:
      url: https://pineapple.secretsmgr.cyberark.cloud/api
      auth:
        jwt:
          account: conjur
          serviceID: cluster1
          serviceAccountRef:
            name: eso-sa
            audiences:
              - https://pineapple.secretsmgr.cyberark.cloud
