apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur-poc-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: conjur-poc-apikey
    kind: SecretStore
  target:
    name: eso-secret-from-conjur-apikey
    creationPolicy: Owner
  data:
  - secretKey: address
    remoteRef:
      key: data/vault/ConjurCloudTestSafe/conjurtestaccount/address