apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur-poc-apikey
spec:
  provider:
    conjur:
      url: https://pineapple.secretsmgr.cyberark.cloud/api
      auth:
        apikey:
          account: conjur
          userRef:
            name: conjur-creds
            key: workloadid
          apiKeyRef:
            name: conjur-creds
            key: apikey
